export { default as Home } from './Home'
export { default as Landing } from './Landing'
export { default as LogIn } from './LogIn'
export { default as Register } from './Register'
export { default as Error } from './Error'
